### ISSUE TITLE
Push docker container usage (CPU/Memory) through node-exporter to our central monitoring

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon-distributed-validator-node#30]
# 🚀 Feature Request

## Problem to be solved

Push docker container host resource usages to central grafana. This will help in triaging if the issue's with charon or the nodes running charon.

Currently, only `charon` and `teku` are allowed to push to central grafana. We want to enable this for `node-exporter` as well in the future.

## Proposed Solution
Allow `node-exporter` job to `remote_write`:

```
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 
```

```
remote_write:
- url: https://your-server.grafana.net/api/prom/push
  write_relabel_configs:
  - source_labels: [job]
    regex: 'node-exporter'
    action: keep
```

## Out of Scope
None
