### ISSUE TITLE
Push prometheus metrics to grafana cloud

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon-distributed-validator-node#8]
## Problem to be solved

We need to push prometheus metrics of charon nodes to our centralized grafana cloud for monitoring the performance of our charon client where it can be grouped by cluster identifiers which will give us deeper view of how our client is performing in public testnets.

## Proposed solution

The following config needs to be added to [this](https://github.com/ObolNetwork/charon-distributed-validator-node/blob/main/prometheus/prometheus.yml) and tested well with distributed nodes:
```
remote_write:
      - url: $GRAFANA_CLOUD_URL
        basic_auth:
          username: $PROM_REMOTE_WRITE_USER
          password: $PROM_REMOTE_WRITE_PASSWORD
```

## Definition of Done

Local distributed nodes' metrics are depicted on central grafana dashboards.
